<?php

use App\InfoImg;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class InfoImgTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        InfoImg::insert([
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '10',
                'name' => '0120 小蝸牛市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0120-Lole-Market/0120-Lole-Market-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '11',
                'name' => '0210 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0210-Moon-Market/0210-Moon-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '11',
                'name' => '0210 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0210-Moon-Market/0210-Moon-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '11',
                'name' => '0210 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0210-Moon-Market/0210-Moon-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '11',
                'name' => '0210 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0210-Moon-Market/0210-Moon-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '12',
                'name' => '0218 寧夏市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0218-Ningxia-Market/0218-Ningxia-Market-07.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '13',
                'name' => '0410 散策市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0410-Walking-Market/0410-Walking-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '13',
                'name' => '0410 散策市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0410-Walking-Market/0410-Walking-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '13',
                'name' => '0410 散策市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0410-Walking-Market/0410-Walking-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '13',
                'name' => '0410 散策市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0410-Walking-Market/0410-Walking-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '13',
                'name' => '0410 散策市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0410-Walking-Market/0410-Walking-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '14',
                'name' => '0507 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0507-Moon-Market/0507-Moon-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '14',
                'name' => '0507 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0507-Moon-Market/0507-Moon-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '14',
                'name' => '0507 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0507-Moon-Market/0507-Moon-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '14',
                'name' => '0507 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0507-Moon-Market/0507-Moon-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '14',
                'name' => '0507 暮暮市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0507-Moon-Market/0507-Moon-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-07.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '15',
                'name' => '0513 微涼市集',
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0513-Breeze-Market/0513-Breeze-Market-08.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '16',
                'name' => '0517 小蝸牛市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0517-Lole-Market/0517-Lole-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '16',
                'name' => '0517 小蝸牛市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0517-Lole-Market/0517-Lole-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '16',
                'name' => '0517 小蝸牛市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0517-Lole-Market/0517-Lole-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '16',
                'name' => '0517 小蝸牛市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0517-Lole-Market/0517-Lole-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '16',
                'name' => '0517 小蝸牛市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0517-Lole-Market/0517-Lole-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '17',
                'name' => '0708 暮暮市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0708-Moon-Market/0708-Moon-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '17',
                'name' => '0708 暮暮市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0708-Moon-Market/0708-Moon-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '17',
                'name' => '0708 暮暮市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0708-Moon-Market/0708-Moon-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '17',
                'name' => '0708 暮暮市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0708-Moon-Market/0708-Moon-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '17',
                'name' => '0708 暮暮市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0708-Moon-Market/0708-Moon-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '18',
                'name' => '0908 草地市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0908-Grassland-Market/0908-Grassland-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '18',
                'name' => '0908 草地市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0908-Grassland-Market/0908-Grassland-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '18',
                'name' => '0908 草地市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0908-Grassland-Market/0908-Grassland-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '18',
                'name' => '0908 草地市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0908-Grassland-Market/0908-Grassland-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '18',
                'name' => '0908 草地市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/0908-Grassland-Market/0908-Grassland-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'info_id' => '19',
                'name' => '1008 微風市集',    
                'content' => 'none',
                'img' => '/img/news/03-Activity-Photoes/1008-Breeze-Market/1008-Breeze-Market-07.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
        ]);
    }
}
