<?php

use App\ShopImg;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ShopImgTableSeeder extends Seeder
{
    /**
     * 有三家假資料
     */
    public function run()
    {
        ShopImg::insert([
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '1',
                'content' => 'Two Day 日日鬆餅',
                'img' => '/img/store/02-Foods/01-TwoDay/01-TwoDay-imgs/TwoDay-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '2',
                'content' => '旅禾 泡芙之家',
                'img' => '/img/store/02-Foods/04-luhopuff/04-luhopuff-imgs/luhopuff-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '3',
                'content' => '森小姐的茶店',
                'img' => '/img/store/02-Foods/05-senstea/05-senstea-imgs/senstea-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '4',
                'content' => '艸水木堂',
                'img' => '/img/store/02-Foods/06-grass364/06-grass364-imgs/grass364-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '5',
                'content' => '三時杏仁',
                'img' => '/img/store/02-Foods/02-ThreeClockAlmonds/02-ThreeClockAlmonds-imgs/ThreeClockAlmonds-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '6',
                'content' => '甜月亮義大利手作冰淇淋',
                'img' => '/img/store/02-Foods/03-DolceLuna/03-DolceLuna-imgs/DolceLuna-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '7',
                'content' => '成真咖啡 台中審計店',
                'img' => '/img/store/02-Foods/07-cometrue-coffee/07-cometrue-coffee-imgs/cometrue-coffee-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '8',
                'content' => '森多水耕植研所',
                'img' => '/img/store/01-Small-objects/01-senduo/01-senduo-imgs/senduo-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '9',
                'content' => '森林島嶼x台中審計店',
                'img' => '/img/store/01-Small-objects/02-forest-islands/forest-islands-imgs/forest-islands-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '10',
                'content' => '愚室實驗所插畫主題商店',
                'img' => '/img/store/01-Small-objects/03-yushilab/03-yushilab-imgs/yushilab-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '11',
                'content' => '小日子商号',
                'img' => '/img/store/01-Small-objects/04-onelittleday/little-day-img/onelittleday-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '12',
                'content' => 'Kou Jewellery',
                'img' => '/img/store/01-Small-objects/05-KouJewellery/05-KouJewellery-imgs/KouJewellery-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '13',
                'content' => '品墨良行',
                'img' => '/img/store/01-Small-objects/06-pin-mo-liang-sing/pin-mo-liang-sing-imgs/pin-mo-liang-sing-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-01.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-02.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-03.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-04.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-05.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
            [
                'shop_id' => '14',
                'content' => 'KerKerland 審計店',
                'img' => '/img/store/01-Small-objects/07-kerkerland/kerkerland-imgs/kerkerland-06.jpg',
                'created_at' => now()->toDateString(),
                'updated_at' => now()->toDateString(),
            ],
        ]);
    }
}
